export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_RESET_PASS_DATA =
  "SET_CURRENT_USER_RESET_PASS_DATA";

export const FLASH_MESSAGE = "FLASH_MESSAGE";
export const CLEAR_CURRENT_FLASH_MESSAGE = "CLEAR_CURRENT_FLASH_MESSAGE";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const GET_SESSION_CART = "GET_SESSION_CART";
export const SESSION_CART_LOADING = "SESSION_CART_LOADING";
export const CLEAR_CURRENT_SESSION_CART = "CLEAR_CURRENT_SESSION_CART";
export const GET_SESSION_CART_BY_ID = "GET_SESSION_CART_BY_ID";
export const PRODUCT_ADDED_IN_SESSION_CART_BY_ID =
  "PRODUCT_ADDED_IN_SESSION_CART_BY_ID";
export const PRODUCT_IN_SESSION_CART_INC_BY_1_ID =
  "PRODUCT_IN_SESSION_CART_INC_BY_1_ID";
export const PRODUCT_IN_SESSION_CART_DEC_BY_1_ID =
  "PRODUCT_IN_SESSION_CART_DEC_BY_1_ID";
export const PRODUCT_IN_SESSION_CART_DELETE_BY_ID =
  "PRODUCT_IN_SESSION_CART_DELETE_BY_ID";

export const GET_WAREHOUSE = "GET_WAREHOUSE";
export const WAREHOUSE_LOADING = "WAREHOUSE_LOADING";
export const GET_WAREHOUSE_BY_ID = "GET_WAREHOUSE_BY_ID";

export const GET_STOCK = "GET_STOCK";
export const STOCK_LOADING = "STOCK_LOADING";

export const CREATE_STOCK_LOADING_START = "CREATE_STOCK_LOADING_START";
export const CREATE_STOCK_LOADING_STOP = "CREATE_STOCK_LOADING_STOP";

export const CLEAR_CURRENT_STOCK = "CLEAR_CURRENT_STOCK";
export const GET_STOCK_BY_ID = "GET_STOCK_BY_ID";
export const STOCK_EDITED_BY_ID = "STOCK_EDITED_BY_ID";
export const ADD_ON_EXISTING_PRODUCT_STOCK = "ADD_ON_EXISTING_PRODUCT_STOCK";
export const REMOVE_ON_EXISTING_PRODUCT_STOCK =
  "REMOVE_ON_EXISTING_PRODUCT_STOCK";

export const GET_SINGLE_PRODUCT_ALL_ITEM_WITH_TOTALQTY_WAREHOUSE_BY_ID =
  "GET_SINGLE_PRODUCT_ALL_ITEM_WITH_TOTALQTY_WAREHOUSE_BY_ID";

export const GET_ORIGIN_WAREHOUSE_PROD_STOCKS =
  "GET_ORIGIN_WAREHOUSE_PROD_STOCKS";

export const GET_ORIGIN_WAREHOUSE_PROD_STOCKS_LOADING =
  "GET_ORIGIN_WAREHOUSE_PROD_STOCKS_LOADING";

export const GET_SESSION_WAREHOUSE_TRANSFER = "GET_SESSION_WAREHOUSE_TRANSFER";

export const GET_ALL_WAREHOUSE_TRANSFER_HISTORY =
  "GET_ALL_WAREHOUSE_TRANSFER_HISTORY";

export const SESSION_WAREHOUSE_TRANSFER_LOADING =
  "SESSION_WAREHOUSE_TRANSFER_LOADING";

export const WAREHOUSE_TRANSFER_HISTORY_LOADING =
  "WAREHOUSE_TRANSFER_HISTORY_LOADING";

export const GET_WAREHOUSE_TRANSFER_HISTORY_BY_DATE =
  "GET_WAREHOUSE_TRANSFER_HISTORY_BY_DATE";

export const GET_WAREHOUSE_TRANSFER_HISTORY_BY_ID =
  "GET_WAREHOUSE_TRANSFER_HISTORY_BY_ID";
export const CLEAR_CURRENT_WAREHOUSE_TRANSFER =
  "CLEAR_CURRENT_WAREHOUSE_TRANSFER";

export const PRODUCT_ADDED_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID =
  "PRODUCT_ADDED_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID";
export const PRODUCT_DELETE_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID =
  "PRODUCT_DELETE_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID";
export const GET_SESSION_WAREHOUSE_TRANSFER_BY_ID =
  "GET_SESSION_WAREHOUSE_TRANSFER_BY_ID";
export const GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING =
  "GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING";
export const GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING_STOP =
  "GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING_STOP";
export const PRODUCT_IN_SESSION_WAREHOUSE_TRANSFER_INC_BY_ID =
  "PRODUCT_IN_SESSION_WAREHOUSE_TRANSFER_INC_BY_ID";

export const GET_NEW_STOCK_HISTORY_DATES = "GET_NEW_STOCK_HISTORY_DATES";

export const GET_NEW_STOCK_HISTORY_DATES_LOADING =
  "GET_NEW_STOCK_HISTORY_DATES_LOADING";

export const GET_NEW_STOCKS_HISTORY_BY_DATE = "GET_NEW_STOCKS_HISTORY_BY_DATE";

export const GET_EXISTING_STOCK_HISTORY_DATES =
  "GET_EXISTING_STOCK_HISTORY_DATES";

export const GET_EXISTING_STOCK_HISTORY_DATES_LOADING =
  "GET_EXISTING_STOCK_HISTORY_DATES_LOADING";

export const GET_EXISTING_STOCKS_HISTORY_BY_DATE =
  "GET_EXISTING_STOCKS_HISTORY_BY_DATE";

export const GET_ADVANCED_INVENTYORY_SEARCH_RESULT =
  "GET_ADVANCED_INVENTYORY_SEARCH_RESULT";

export const GET_ADVANCED_INVENTYORY_SEARCH_RESULT_LOADING =
  "GET_ADVANCED_INVENTYORY_SEARCH_RESULT_LOADING";

export const GET_DELETED_STOCK_HISTORY_DATES_LOADING =
  "GET_DELETED_STOCK_HISTORY_DATES_LOADING";

export const GET_DELETED_STOCKS_HISTORY_BY_DATE =
  "GET_DELETED_STOCKS_HISTORY_BY_DATE";

export const GET_COMPANY = "GET_COMPANY";
export const COMPANY_LOADING = "COMPANY_LOADING";
export const GET_BUYER_COMPANY = "GET_BUYER_COMPANY";
export const BUYER_COMPANY_LOADING = "BUYER_COMPANY_LOADING";
export const GET_COMPANY_BY_ID = "GET_COMPANY_BY_ID";
export const GET_COMPANY_BY_Name = "GET_COMPANY_BY_Name";

export const UPDATE_MIN_REQUIRED_NOTIFY_QTY = "UPDATE_MIN_REQUIRED_NOTIFY_QTY";

export const GET_ADDEXISTING_STOCK_HISTORY_DATES =
  "GET_ADDEXISTING_STOCK_HISTORY_DATES";

export const GET_ADDEXISTING_STOCKS_HISTORY_DATES_LOADING =
  "GET_ADDEXISTING_STOCKS_HISTORY_DATES_LOADING";

export const GET_ADDEXISTING_STOCKS_HISTORY_BY_DATE =
  "GET_ADDEXISTING_STOCKS_HISTORY_BY_DATE";

export const GET_ADDEXISTING_STOCKS_HISTORY_BY_DATE_LOADING =
  "GET_ADDEXISTING_STOCKS_HISTORY_BY_DATE_LOADING";

export const GET_REMOVEEXISTING_STOCK_HISTORY_DATES =
  "GET_REMOVEEXISTING_STOCK_HISTORY_DATES";
export const GET_REMOVEEXISTING_STOCKS_HISTORY_DATES_LOADING =
  "GET_REMOVEEXISTING_STOCKS_HISTORY_DATES_LOADING";

export const GET_REMOVEEXISTING_STOCKS_HISTORY_BY_DATE =
  "GET_REMOVEEXISTING_STOCKS_HISTORY_BY_DATE";

export const GET_REMOVEEXISTING_STOCKS_HISTORY_BY_DATE_LOADING =
  "GET_REMOVEEXISTING_STOCKS_HISTORY_BY_DATE_LOADING";

export const GET_EDITEXISTING_STOCK_HISTORY_DATES =
  "GET_EDITEXISTING_STOCK_HISTORY_DATES";

export const GET_EDITEXISTING_STOCKS_HISTORY_DATES_LOADING =
  "GET_EDITEXISTING_STOCKS_HISTORY_DATES_LOADING";

export const GET_EDITEXISTING_STOCKS_HISTORY_BY_DATE =
  "GET_EDITEXISTING_STOCKS_HISTORY_BY_DATE";

export const GET_EDITEXISTING_STOCKS_HISTORY_BY_DATE_LOADING =
  "GET_EDITEXISTING_STOCKS_HISTORY_BY_DATE_LOADING";

export const GET_COMPANY_SALES_ORDER = "GET_COMPANY_SALES_ORDER";
export const COMPANY_SALES_ORDER_LOADING = "COMPANY_SALES_ORDER_LOADING";
export const COMPANY_SALES_ORDER_LOADING_STOP =
  "COMPANY_SALES_ORDER_LOADING_STOP";

export const GET_COMPANY_DUMMY_SALES_ORDER = "GET_COMPANY_DUMMY_SALES_ORDER";
export const COMPANY_DUMMY_SALES_ORDER_LOADING =
  "COMPANY_DUMMY_SALES_ORDER_LOADING";
export const COMPANY_DUMMY_SALES_ORDER_LOADING_STOP =
  "COMPANY_DUMMY_SALES_ORDER_LOADING_STOP";

export const GET_DUMMY_COMPANY_SALES_ORDER_ID =
  "GET_DUMMY_COMPANY_SALES_ORDER_ID";

export const GET_COMPANY_SALES_ORDER_ID = "GET_COMPANY_SALES_ORDER_ID";

export const GET_COMPANY_CANCELLED_SALES_ORDER =
  "GET_COMPANY_CANCELLED_SALES_ORDER";
export const COMPANY_CANCELLED_SALES_ORDER_LOADING =
  "COMPANY_CANCELLED_SALES_ORDER_LOADING";

export const GET_COMPANY_CANCELLED_SALES_ORDER_ID =
  "GET_COMPANY_CANCELLED_SALES_ORDER_ID";

export const CANCELLED_SALES_ORDER_BY_ID_LOADING_START =
  "CANCELLED_SALES_ORDER_BY_ID_LOADING_START";
export const CANCELLED_SALES_ORDER_BY_ID_LOADING_STOP =
  "CANCELLED_SALES_ORDER_BY_ID_LOADING_STOP";

export const GET_MIN_QTY_REQ_ITEMS = "GET_MIN_QTY_REQ_ITEMS";
export const GET_MIN_QTY_REQ_ITEMS_LOADING = "GET_MIN_QTY_REQ_ITEMS_LOADING";

export const GET_MAX_QTY_ITEMS = "GET_MAX_QTY_ITEMS";
export const GET_MAX_QTY_ITEMS_LOADING = "GET_MAX_QTY_ITEMS_LOADING";

export const GET_LEAST_SOLD_ITEMS = "GET_LEAST_SOLD_ITEMS";
export const GET_LEAST_SOLD_ITEMS_LOADING = "GET_LEAST_SOLD_ITEMS_LOADING";

export const GET_MAX_QTY_SOLD_ITEMS = "GET_MAX_QTY_SOLD_ITEMS";
export const GET_MAX_QTY_SOLD_ITEMS_LOADING = "GET_MAX_QTY_SOLD_ITEMS_LOADING";

export const GET_TOTAL_SALES_BY_BUYER_WISE = "GET_TOTAL_SALES_BY_BUYER_WISE";
export const GET_TOTAL_SALES_BY_BUYER_WISE_LOADING =
  "GET_TOTAL_SALES_BY_BUYER_WISE_LOADING";

export const GET_TOTAL_SALES_BY_STATE_WISE = "GET_TOTAL_SALES_BY_STATE_WISE";
export const GET_TOTAL_SALES_BY_STATE_WISE_LOADING =
  "GET_TOTAL_SALES_BY_STATE_WISE_LOADING";

export const GET_TOTAL_SALES_BY_WAREHOUSE_WISE =
  "GET_TOTAL_SALES_BY_WAREHOUSE_WISE";
export const GET_TOTAL_SALES_BY_WAREHOUSE_WISE_LOADING =
  "GET_TOTAL_SALES_BY_WAREHOUSE_WISE_LOADING";

export const GET_INVENTORY_USERS = "GET_INVENTORY_USERS";
export const GET_INVENTORY_USERS_LOADING = "GET_INVENTORY_USERS_LOADING";

export const GET_BILLING_USERS = "GET_BILLING_USERS";
export const GET_BILLING_USERS_LOADING = "GET_BILLING_USERS_LOADING";

export const GET_CHANGED_PASSWORD_LOADING_START =
  "GET_CHANGED_PASSWORD_LOADING_START";
export const GET_CHANGED_PASSWORD_LOADING_STOP =
  "GET_CHANGED_PASSWORD_LOADING_STOP";

export const GET_FORGOT_PASSWORD_LOADING_START =
  "GET_FORGOT_PASSWORD_LOADING_START";
export const GET_FORGOT_PASSWORD_LOADING_STOP =
  "GET_FORGOT_PASSWORD_LOADING_STOP";

export const COMPANY_UPLOAD_SALES_ORDER_BILLT_LOADING =
  "COMPANY_UPLOAD_SALES_ORDER_BILLT_LOADING";
export const COMPANY_UPLOAD_SALES_ORDER_BILLT_STOP =
  "COMPANY_UPLOAD_SALES_ORDER_BILLT_STOP";

export const COMPANY_SALES_ORDER_EMAIL_SEND_INVOICE_BILLT_LOADING =
  "COMPANY_SALES_ORDER_EMAIL_SEND_INVOICE_BILLT_LOADING";
export const COMPANY_SALES_ORDER_EMAIL_SEND_INVOICE_BILLT_STOP =
  "COMPANY_SALES_ORDER_EMAIL_SEND_INVOICE_BILLT_STOP";

export const GET_PENDING_BILLTY_SALES_ORDER = "GET_PENDING_BILLTY_SALES_ORDER";
export const GET_PENDING_BILLTY_UPLOAD_LOADING_START =
  "GET_PENDING_BILLTY_UPLOAD_LOADING_START";
export const GET_PENDING_BILLTY_UPLOAD_LOADING_STOP =
  "GET_PENDING_BILLTY_UPLOAD_LOADING_STOP";
